name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            pyinstaller-ext: .exe
          - os: ubuntu-latest
            pyinstaller-ext: "_linux"
          - os: macos-latest
            pyinstaller-ext: "_macos"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pyinstaller loguru pycryptodome requests

      - name: Build base executable
        run: pyinstaller -F main.py -n WeBan${{ matrix.pyinstaller-ext }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            dist/WeBan${{ matrix.pyinstaller-ext }}
          generate_release_notes: true
